### ISSUE TITLE
Sorting production chain icons

### ISSUE THREAD

**Issue by toorudez** [pyanodon/pycoalprocessing#330] opened 2023-04-30 16:10 UTC
The recipe window icons do not appear to be sorted for each recipe chain. In particular, I was looking at the Niobium Plate chain, and the recipe icons are scattered throughout the recipe window. Can they be sorted similar to the ones in the Raw Ore window?

**Comment by notnotmelon** [comment] 2024-02-19 23:08
Thanks for the report.
This is a duplicate of https://github.com/pyanodon/pybugreports/issues/358
Closing

**Closed by notnotmelon** 2024-02-19 23:08 UTC
