### ISSUE TITLE
Placeholder tech

### ISSUE THREAD

**Issue by ShadowGlass0** [pyanodon/pycoalprocessing#86] opened 2021-07-19 04:18 UTC
Reminder to remove "placerholder" tech.

**Comment by ShadowGlass0** [comment] 2021-07-19 22:50
Current recipes in Placeholder tech (edit this as they get cleared out):
- Crude oil from Oleochemicals
- Filtration media (only used for the above)
- Crude oil from Aromatics + Syngas
- Syngas from Coal dust
- Methanol + Petgas from Organic solvent + Olefins
- Heavy oil from Oleochemicals + Sulfuric acid
- Heavy oil from Oleochemicals + sulfuric acid + chromium + water
- Wood to coal
- Coal dust from coal
- Stone brick from rich clay
- Syngas from Oleochemicals
- Heavy oil combustion
- Acetylene combustion (acetylene is not used from anything else)
- Coal gas from Heavy oil
- Copper & Iron from tar
- Raw borax & Niobium ore from tar
- Aromatics from Refsyngas + Organic matter
- Quenching tower (used from the above 2)

**Comment by kingarthur91** [comment] 2021-09-07 06:21
moving this from "bug" to "wip" as its a known issue and not a bug. prefer the bug label be reserved for things that are actually broken

**Closed** 2021-09-21 23:03 UTC
Labels: WIP
